# Example configuration file for a COLIBRE-like simulation

# Location of your other .yml files that are passed to the
# velociraptor auto plotter (these describe your scaling)
# relation figures. Also required is the registration file
# in the case where you have non-catalogue properties
# used in the autoplotter.
auto_plotter_directory: auto_plotter
auto_plotter_registration: registration.py

# Location of the 'observational data' repository and its compiled
# contents.
observational_data_directory: ../observational_data

# Style sheet to be used throughout with plotting
matplotlib_stylesheet: mnras.mplstyle

# Jinja2 template that gets fed the swiftsimio metadata
# object for you to describe the run with.
description_template: description.html

# Location and description of additional figures
scripts:
  - filename: scripts/number_of_agn_thermal_injections.py
    caption: A histogram showing the cumulative number of black holes with a given total number of thermal energy injections (less than or equal to the number of particles heated) the black hole has had throughout the simulation.
    output_file: num_agn_thermal_injections.png
    section: Black Holes
    title: Cumulative number of AGN thermal injections
  - filename: scripts/max_temperatures.py
    caption: Maximal temperature recorded by gas particles throughout the entire simulation.
    output_file: gas_max_temperatures.png
    section: Maximal Temperatures
    title: Maximal Temperature reached by gas particles
  - filename: scripts/max_temperature_redshift.py
    caption: A diagram displaying maximal temperatures vs redshifts at which they were reached. The pixel colour indicates the number of stellar + gas particles in the pixel.
    output_file: max_temperature_redshift.png"
    section: Maximal Temperatures
    title: Maximal Temperature-Redshift