# Example configuration file for a COLIBRE-like simulation
# Location of your other .yml files that are passed to the
# velociraptor auto plotter (these describe your scaling)
# relation figures. Also required is the registration file
# in the case where you have non-catalogue properties
# used in the autoplotter.
auto_plotter_directory: auto_plotter
auto_plotter_registration: registration.py

# Location of the 'observational data' repository and its compiled
# contents.
observational_data_directory: ../observational_data

# Style sheet to be used throughout with plotting
matplotlib_stylesheet: mnras.mplstyle

# Jinja2 template that gets fed the swiftsimio metadata
# object for you to describe the run with.
description_template: description.html

# Location and description of additional figures
scripts:
  - filename: scripts/stellar_abundances_FeH_CFe_GALAH.py
    caption: '[Fe/H] vs [C/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [C/H]Sun = 8.43. The median [C/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the GALAH survey (Buder et al. 2021). Contours use a log scale with 0.04 bin size and a minimum star count of 10. All recommended flags are applied to GALAH data to select stars (SN, FE/H and X/Fe quality flags).'
    output_file: stellar_abundances_FeH_CFe_GALAH.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [C/Fe]'
  - filename: scripts/stellar_abundances_FeH_CFe_APOGEE.py
    caption: '[Fe/H] vs [C/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [C/H]Sun = 8.43. The median [C/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_FeH_CFe_APOGEE.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [C/Fe]'
  - filename: scripts/stellar_abundances_FeH_NFe_APOGEE.py
    caption: '[Fe/H] vs [N/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [N/H]Sun = 7.83. The median [N/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_FeH_NFe_APOGEE.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [N/Fe]'
  - filename: scripts/stellar_abundances_FeH_OFe_GALAH.py
    caption: '[Fe/H] vs [O/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [O/H]Sun = 8.69. The median [O/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the GALAH survey (Buder et al. 2021). Contours use a log scale with 0.04 bin size and a minimum star count of 10. All recommended flags are applied to GALAH data to select stars (SN, FE/H and X/Fe quality flags).'
    output_file: stellar_abundances_FeH_OFe_GALAH.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [O/Fe]'
  - filename: scripts/stellar_abundances_FeH_OFe_APOGEE.py
    caption: '[Fe/H] vs [O/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [O/H]Sun = 8.69. The median [O/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_FeH_OFe_APOGEE.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [O/Fe]'
  - filename: scripts/stellar_abundances_FeH_OFe.py
    caption: '[Fe/H] vs [O/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [O/H]Sun = 8.69. The median [O/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the works of Mishenina+99, Israelian+98, Cayrel+04, Bai+04, Zhang+05, Koch+08. Most of these works assume Grevesser & Anders (1989) values for solar metallicity, their were corrected  to Asplund+09. Additional data includes Fornax (Letarte+07), Carina (Kock+05), Sculptor (Geisler+05) and  Sagittarious (Sbordone+07).'
    output_file: stellar_abundances_FeH_OFe.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [O/Fe]'
  - filename: scripts/stellar_abundances_FeH_MgFe_GALAH.py
    caption: '[Fe/H] vs [Mg/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [Mg/H]Sun = 7.6. The median [Mg/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the GALAH survey (Buder et al. 2021). Contours use a log scale with 0.04 bin size and a minimum star count of 10. All recommended flags are applied to GALAH data to select stars (SN, FE/H and X/Fe quality flags).'
    output_file: stellar_abundances_FeH_MgFe_GALAH.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [Mg/Fe]'
  - filename: scripts/stellar_abundances_FeH_MgFe_APOGEE.py
    caption: '[Fe/H] vs [Mg/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [Mg/H]Sun = 7.6. The median [Mg/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_FeH_MgFe_APOGEE.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [Mg/Fe]'
  - filename: scripts/stellar_abundances_FeH_MgFe.py
    caption: '[Fe/H] vs [Mg/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [Mg/H]Sun = 7.6. The median [Mg/Fe] vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW, Carina, Fornax, Sculptor and Sagittarious corresponds to a data compilation presented by Tolstoy, Hill & Tosi (2009) and extracted by Rob Crain. Note solar metallicity of Grevesser & Anders (1989) was corrected to Asplund+09.'
    output_file: stellar_abundances_FeH_MgFe.png
    section: Stellar Metal Abundances
    title: '[Fe/H] vs [Mg/Fe]'
  - filename: scripts/stellar_abundances_OH_OFe.py
    caption: '[O/H] vs [O/Fe] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5 and [O/H]Sun = 8.69. The median [O/Fe] vs median [O/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_OH_OFe.png
    section: Stellar Metal Abundances
    title: '[O/H] vs [O/Fe]'
  - filename: scripts/stellar_abundances_OH_MgFe.py
    caption: '[O/H] vs [Mg/Fe] using Asplund et al. (2009) values for [O/H]Sun = 8.69 and [Mg/H]Sun = 7.6. The median [Mg/Fe] vs median [O/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles. The observational data for MW compiles the data from the APOGEE survey (Holtzman et al. 2018). Contours use a log scale with 0.04 bin size and a minimum star count of 10.' 
    output_file: stellar_abundances_OH_MgFe.png
    section: Stellar Metal Abundances
    title: '[O/H] vs [Mg/Fe]'
  - filename: scripts/stellar_abundances_FeH_Fe_snia_fraction.py
    caption: 'The mass fraction of Fe from SNIa vs [Fe/H] using Asplund et al. (2009) values for [Fe/H]Sun = 7.5. The median SNIa Fe fraction vs median [Fe/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles.'
    output_file: stellar_abundances_FeH_Fe_snia_fraction.png
    section: Stellar Metal Abundances
    title: 'Fraction of Fe from SNIa vs [Fe/H]'
  - filename: scripts/stellar_abundances_OH_Fe_snia_fraction.py
    caption: 'The mass fraction of Fe from SNIa vs [O/H] using Asplund et al. (2009) values for [O/H]Sun = 8.69. The median SNIa Fe fraction vs median [O/H] is indicated by the solid curve(s). The scatter points show abundances of individual stellar particles.'
    output_file: stellar_abundances_OH_Fe_snia_fraction.png
    section: Stellar Metal Abundances
    title: 'Fraction of Fe from SNIa vs [O/H]'

